name: Build and Release Version

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.303'  # Usa la versión de .NET que prefieras

    - name: Restore dependencies
      run: dotnet restore ./Bank/Bank.WebApi/Bank.WebApi.csproj

    - name: Build project
      run: dotnet build ./Bank/Bank.WebApi/Bank.WebApi.csproj --configuration Release

    - name: Run unit tests
      run: dotnet test ./Bank/Bank.WebApi/Bank.WebApi.csproj --configuration Release

    - name: Publish project
      run: dotnet publish ./Bank/Bank.WebApi/Bank.WebApi.csproj --configuration Release --output ./publish

    - name: Create release asset
      run: |
        zip -r release.zip ./publish
        echo "Release zip created"

    - name: Create release tag
      run: |
        git tag v$(date +'%Y%m%d%H%M%S')  # Crea una etiqueta con una fecha y hora única
        git push origin --tags  # Empuja la etiqueta recién creada
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
